- name: Create var from file
  set_fact:
    script: "{{ lookup( 'file', 'list_volumes.ps1' ) }}"

- name: Run script on host
  ansible.windows.win_shell: |
      {{ script }}
  register: output

- ansible.builtin.debug:
    var: output.stdout
    