- name: Create script content from file
  set_fact:
    script_to_run: "{{ lookup( 'file', script ) }}"

- name: Run script on host
  ansible.windows.win_shell: |
      {{ script_to_run }} {{ param }}
  register: output

- name: Script output 
  ansible.builtin.debug:
    var: output.stdout_lines
    
- name: Script error
  ansible.builtin.debug:
    var: output.stderr