---
# TAGS - add_eingram_user, add_ansible_user, chrony, snmpd, splunk, container_host, webapps, node_exporter, windows_exporter, install_core_pkgs
- name: Run site baseline plays
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  
  roles:
    - role: add-eingram-user
      tags:
        - never
        - add-eingram-user
    - role: add-ansible-user
      tags:
        - never
        - add-ansible-user
    - role: chrony
      tags:
        - never
        - chrony
    - role: install-core-pkgs
      tags:
        - never
        - install-core-pkgs
    - role: container_host
      tags:
        - never
        - container-host
    - role: splunk-uf
      tags:
        - never
        - splunk-uf
    - role: snmpd
      tags:
        - never
        - snmpd
    - role: node-exporter
      tags:
        - never
        - node-exporter
    - role: webapps
      tags:
        - never
        - webapps
    - role: rhel-sub-add
      tags:
        - never
        - rhel-sub-add
    - role: rhel-sub-del 
      tags:
        - never
        - rhel-sub-del
    - role: windows-exporter
      tags:
        - never
        - windows-exporter

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become_user: poduser
  become_method: sudo

  roles:
    - role: prometheus-target-update-nix
      tags:
        - never
        - node-exporter
    - role: prometheus-target-update-win
      tags:
        - never
        - windows-exporter

