---
- name: TEST
  hosts: localhost
  become: false

  tasks:

    - ansible.builtin.include_vars: 
        file: "{{ item }}"
      loop:
        - "vars/secret.yaml"
        - "vars/secret2.yaml"
        # - "{{ playbook_dir }}/secret2.yaml"

    - debug: var=secret

    - debug: var=secret2
