---
- name: TEST Playbook
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: TEST - Sleep 10
      ansible.builtin.shell: sleep 1
        
    - name: TEST - Pause
      ansible.builtin.pause:
        seconds: 1

