---
- name: Run tasks
  hosts: "HL-DC1.homelab.local"
  gather_facts: false
  become: true

  tasks:

    - name: Test
      ansible.windows.win_shell: |
       get-ciminstance win32_process -filter "name = 'fontdrvhost.exe'" |select commandline
       write-host "test"
      register: process

    - debug:
        var: process.stdout

      # - debug: msg="Splunk is running"
      #   when: process.stdout is search("splund.exe")
...