---
- name: TEST
  hosts: localhost
  become: false

  vars:
    roles:
      - test
      - test2
  
  tasks:

    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ roles }}"