---
- name: Run kafka producer script
  ansible.builtin.script: test_producer.py
  args:
    executable: python3
  register: producer_output

- name: Print producer output
  ansible.builtin.debug:
    msg: "{{ producer_output.stdout }}"

- name: Print producer error
  ansible.builtin.debug:
    msg: "{{ producer_output.stderr }}"
  when: producer_output.stderr is defined and producer_output.stderr != ""
