- name: Copy script to host
  ansible.windows.win_copy:
    src: "{{ role_path }}/files/{{ category }}/{{ script }}"
    dest: c:\temp\

- name: Run script via win_shell
  ansible.builtin.include_role:
    name: winshell
  when: schtask == "disabled"

- name: Run script via scheduled task
  ansible.builtin.include_role:
    name: win_schtasks
  when: schtask == "enabled"

- name: Clean up script
  ansible.windows.win_file:
    path: c:\temp\{{ script }}
    state: absent