---
- name: Install Samba
  ansible.builtin.package:
    name: samba
    state: present

- name: Enable smb and nmb services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - smb
    - nmb

- name: Enable firewall rules for samba
  ansible.builtin.firewalld:
    service: samba
    permanent: true
    state: enabled
  notify: Reloead firewalld

- name: Add shareaccess user
  ansible.builtin.user:
    name: shareaccess
    password: $6$CRvGabIziUpx7Z5H$8dF37lNx/1d/e4XOvWjzQFkmJjBoLMNOI6M7ADKfCssptb/EI.k1IrTWz3gVj/El.1RfqLcGkrd3w0kZ7T/KM0

- name: Add smb.conf
  ansible.builtin.copy:
    src: smb.conf
    dest: /etc/samba
    backup: true
    mode: '0644'
  notify: Reload smb