---
- name: Install Samba
  ansible.builtin.package:
    name: samba
    state: present

- name: Enable smb and nmb services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - smb
    - nmb

- name: Enable firewall rules for samba
  ansible.builtin.firewalld:
    service: samba
    permanent: true
    state: enabled
  notify: Restart firewalld

- name: Add shareaccess user
  ansible.builtin.user:
    name: shareaccess
    password: $6$CRvGabIziUpx7Z5H$8dF37lNx/1d/e4XOvWjzQFkmJjBoLMNOI6M7ADKfCssptb/EI.k1IrTWz3gVj/El.1RfqLcGkrd3w0kZ7T/KM0

- name: Add eingram user to shareaccess group (for access to Shared)
  ansible.builtin.user:
    name: eingram
    groups: shareaccess
    append: true

- name: Add eingram user to poduser group (for access to PlexMedia)
  ansible.builtin.user:
    name: eingram
    groups: poduser
    append: true
    
- name: Allow samba shares with selinux
  community.general.sefcontext:
    target: '/mnt/pool0(/.*)?'
    setype: samba_share_t
    state: present

- name: Apply new SELinux file context to filesystem
  ansible.builtin.command: restorecon -R /mnt/pool0

- name: Add smb.conf
  ansible.builtin.copy:
    src: smb.confls
    dest: /etc/samba
    backup: true
    mode: '0644'
  notify: Reload smb