---
- name: Apply security updates
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
    security: true
  register: new_build_update_packages

- name: Update installed kernel packages
  ansible.builtin.dnf:
    name: "kernel*"
    state: latest
    update_only: true

- name: Set up chrony
  ansible.builtin.include_role:
    name: eingram23.linux.chrony

- name: Install core packages
  ansible.builtin.include_role:
    name: eingram23.linux.install_core_pkgs

- name: Add admin user {{ user_item }}
  ansible.builtin.include_role:
    name: eingram23.linux.user_mgmt
    tasks_from: add_user
  vars:
    user_account: "{{ user_item }}"
    user_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/ansible:ssh_password') }}"
    admin_user: "yes"
  loop:
    - ansible
    - eingram
  loop_control:
    loop_var: user_item

- name: Install root certificate into trusted store
  ansible.builtin.include_role:
    name: eingram23.linux.certificates

- name: Enable fstrim timer
  ansible.builtin.systemd_service:
    name: fstrim.timer
    state: started
    enabled: true

- name: Journald tasks
  notify:
    - Restart journald
    - Restart server
  block:
    - name: Copy journald.conf to remote host
      ansible.builtin.copy:
        src: journald.conf
        dest: /etc/systemd/journald.conf
        mode: "0644"

    - name: Enable journald persistent storage
      ansible.builtin.file:
        path: /var/log/journal
        state: directory
        owner: root
        group: systemd-journal
        mode: "2755"

- name: Install RLP packages
  ansible.builtin.include_role:
    name: eingram23.linux.{{ rlp_item.key }}
  vars:
    task: "{{ rlp_item.value.task }}"
    version: "{{ rlp_item.value.version }}"
  loop: "{{ new_build_rlp_packages | dict2items }}"
  loop_control:
    loop_var: rlp_item

- name: Check if server needs reboot
  ansible.builtin.command: needs-restarting
  register: new_build_needs_restarting
  changed_when: new_build_needs_restarting.rc !=0
  notify: Restart server
