---
- name: Proxmox tasks
  when: "'proxmox' in group_names"
  block:
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Remove enterprise repositories
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/{{ ent_repo_item }}
        state: absent
      loop:
        - pve-enterprise.sources
        - ceph.sources
      loop_control:
        loop_var: ent_repo_item

    - name: Add no-subscription repositories
      ansible.builtin.copy:
        src: "{{ nonent_repo_item }}"
        dest: /etc/apt/sources.list.d
        owner: root
        group: root
        mode: '0644'
      loop:
        - proxmox.sources
        - ceph.sources
      loop_control:
        loop_var: nonent_repo_item

    - name: Update repository cache
      ansible.builtin.apt:
        update_cache: true

- name: Non-Proxmox tasks
  when: "'proxmox' not in group_names"
  block:
    - name: Set up chrony
      ansible.builtin.include_role:
        name: eingram23.linux.chrony

    - name: Install core packages
      ansible.builtin.include_role:
        name: eingram23.linux.install_core_pkgs

- name: Add admin user {{ user_item }}
  ansible.builtin.include_role:
    name: eingram23.linux.user_mgmt
    tasks_from: add_user
  vars:
    user_account: "{{ user_item }}"
    user_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/ansible:ssh_password') }}"
    admin_user: "yes"
  loop:
    - ansible
    - eingram
  loop_control:
    loop_var: user_item

- name: Install root certificate into trusted store
  ansible.builtin.include_role:
    name: eingram23.linux.certificates
