---
- name: Uninstall windows_exporter if present
  ansible.windows.win_package:
    product_id: '{344EDA7B-3B94-4E58-AD9C-BF019081C485}'
    state: absent

- name: Download grafana agent installer to host
  ansible.windows.win_get_url:
    url: https://github.com/grafana/agent/releases/download/{{ ver }}/grafana-agent-installer.exe.zip
    dest: c:\temp\grafana-agent-installer.exe.zip

- name: Unzip installer
  community.windows.win_unzip:
    src: c:\temp\grafana-agent-installer.exe.zip
    dest: c:\temp\grafana-agent-installer-{{ ver }}
    creates: c:\temp\grafana-agent-installer-{{ ver }}
    delete_archive: false

- name: Run installer
  ansible.windows.win_shell: |
    c:\temp\grafana-agent-installer-{{ ver }}\grafana-agent-installer.exe /S

- name: Create agent config on host
  ansible.windows.win_template:
    src: agent-config.yaml.j2
    dest: c:\program files\grafana agent\agent-config.yaml
  notify: Restart grafana agent