- ansible.windows.win_shell: |
    get-ciminstance win32_process -filter "name = 'splunkd.exe'" |select commandline
  retries: 2
  delay: 1
  until: process.stdout is search("splund.exe")
  register: process
  # ignore_errors: yes