---
- name: Run this to allow passwordless ssh and passwordless sudo 
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  
  tasks:
  
    - name: Create user .ssh dir
      file:
        path: "/home/ansible/.ssh"
        owner: ansible
        group: ansible
        mode: 0755
        state: directory

    - name: Create authorized_keys if not already existing
      file:
        path: "/home/ansible/.ssh/authorized_keys"
        owner: ansible
        group: ansible
        mode: 0600
        state: touch

    - name: Add public key
      lineinfile:
        path: "/home/ansible/.ssh/authorized_keys"
        line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwwvtM55JcbHVFcpq6uJAZ5qZj4z1FI0fYzTwLOm7Xef9kCYKtwBqNH/ixWfYbeM3qKfwP3JrdldEVi5cJauWt8YzHnAAeBcKkHJk47rI26P+DuLfnfnrX5PkIkwX7dUl4C/4ShJNsgTquI9xdwGWHwGpp9NZNTx+Z02A7/ANpCVjGYqDAahlhXYXAr3wEJ7wZucGgbNF8Ru/vlhqdYBXPKxcTW+rIT+wt6D+48bmmwWRZw7W06EBPYSArpiNuonT4ChFb8Zz8ZcFpAde71ya12GjPnroH3Fq53+3t+CTINcMEJPjiOBUy+q61L7QpCVKW9LLhqpxsInUKtZjPDdP080htSPDstoHEDGqqdPWrszfazIwEJZkoLp6eMnEWztB+DNNGuZT4l/tGs6uSL9tuUjuitLSO5zPxrY2fPJm4iZrx294UrmPooUm3LNojlgZ96N9FxPxx1DBg8x6PJgRF24RmHh1oAwBToFn8BwIfjdCe728b1qsxH/LUCKiZrnc= edwardingram@Edwards-MBP.local.lan"

    - name: Create sudoers.d entry
      file:
        path: "/etc/sudoers.d/ansible"
        owner: root
        group: root
        mode: 0644
        state: touch

    - name: Add sudo entry
      lineinfile:
        path: "/etc/sudoers.d/ansible"
        line: "ansible ALL=(ALL:ALL) NOPASSWD: ALL"
        