---
- name: Setup new linux server for Homelab environment
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true
  become_method: ansible.builtin.sudo
  strategy: free

  tasks:

    - name: Include new_build role
      ansible.builtin.include_role:
        name: eingram23.homelab.new_build
