---
- name: Test
  hosts: localhost
  become: false

  tasks:

    - name: Task 1 - Failure
      ansible.builtin.debug:
        msg: "This task is skipped"
      when: true

    - name: Task 1 - Success
      ansible.builtin.debug:
        msg: "This task is successful"
      when: false
