---
- name: Run tasks
  hosts: all
  gather_facts: false
  become: true
  # become_user: "{{ ansible_user }}"

  tasks:

    - name: sleep
      ansible.windows.win_shell: |
        start-sleep 999999
        